version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env  # Specify the path to your .env file
    command: ["make automatic && pm2 logs"]
    volumes:
      - ./broadcast:/app/broadcast
      - ./cache:/app/cache
      
