[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
optimizer = true
optimizer-runs = 2_000


[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
gnosis = "${RPC_GNOSIS}"
goerli = "${RPC_GOERLI}"
chiado = "${RPC_CHIADO}"


[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}
chiado={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=10200}
goerli={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=5}

[fuzz]